Disable post-commit git hook (for now)

diff --git a/links/git-hook-post-commit b/links/git-hook-post-commit
--- a/links/git-hook-post-commit
+++ b/links/git-hook-post-commit
@@ -4,20 +4,28 @@ if [ "$(git branch --show-current)" != "main" ]; then
   exit
 fi
 
-original_stash_size=$(git stash list | wc -l)
-new_stash_size=$original_stash_size
+echo "+============== POST-COMMIT HOOK ===============+"
+echo "|                                               |"
+echo "| Don't forget to rebase work-stuff onto main!! |"
+echo "|                                               |"
+echo "+===============================================+"
 
-cleanup() {
-  if (( new_stash_size > original_stash_size )); then
-    git stash pop -q
-  fi
-  git switch main -q
-}
-trap cleanup EXIT
+# TODO: There's a bit more work to do here
 
-# stash changes before switching
-git stash -a -q 2>/dev/null
-new_stash_size=$(git stash list | wc -l)
+# original_stash_size=$(git stash list | wc -l)
+# new_stash_size=$original_stash_size
 
-git switch work-stuff -q
-git rebase main -q
+# cleanup() {
+#   if (( new_stash_size > original_stash_size )); then
+#     git stash pop -q
+#   fi
+#   git switch main -q
+# }
+# trap cleanup EXIT
+
+# # stash changes before switching
+# git stash -a -q 2>/dev/null
+# new_stash_size=$(git stash list | wc -l)
+
+# git switch work-stuff -q
+# git rebase main -q
