Banners when installing
also includes a bunch of linter changes

diff --git a/src/install_vim b/src/install_vim
--- a/src/install_vim
+++ b/src/install_vim
@@ -1,16 +1,17 @@
 #!/bin/bash
 set -x
 
-echo "Setting up Vim"
+echo "================================================================================"
+echo "| Installing Vim                                                               |"
+echo "================================================================================"
 
 ARTIFACTS_DIR="${ARTIFACTS_DIR:-$(mktemp -d)}"
 
-install_vim()
-{
+install_vim() {
   vim_exists=$(command -v vim)
   if [ -n "$vim_exists" ]; then
-      # Vim exists. Remove it
-      sudo apt-get -qq remove vim vim-runtime gvim
+    # Vim exists. Remove it
+    sudo apt-get -qq remove vim vim-runtime gvim
   fi
 
   # Install make, gcc, and curses. These are dependencies
@@ -20,29 +21,33 @@ install_vim()
   sudo apt-get install -y -q libx11-dev libxtst-dev libxt-dev libsm-dev libxpm-dev
 
   # Download, configure, build, and install
-  tag=$(curl -s https://github.com/vim/vim/tags| \
-    awk 'BEGIN {FS="/"} /\/vim\/vim\/archive\/.*tar.*/ {print $7}' | \
-    sort -r | \
-    head -n1 | \
-    cut -f1 -d\"
+  tag=$(
+    curl -s https://github.com/vim/vim/tags |
+      awk 'BEGIN {FS="/"} /\/vim\/vim\/archive\/.*tar.*/ {print $7}' |
+      sort -r |
+      head -n1 |
+      cut -f1 -d\"
   )
   dirname="$ARTIFACTS_DIR/vim"
   mkdir -p "$dirname"
   tarfile="$dirname/$tag"
   curl -L "https://github.com/vim/vim/archive/$tag" -o "$tarfile"
   tar -zxf "$tarfile" -C "$dirname" --strip-components 1
-  cd "$dirname" || (echo "Couldn't cd to directory [$dirname]"; exit)
+  cd "$dirname" || (
+    echo "Couldn't cd to directory [$dirname]"
+    exit
+  )
 
   ./configure --with-features=huge \
-              --enable-multibyte \
-              --enable-rubyinterp=yes \
-              --enable-python3interp=yes \
-              --enable-perlinterp=yes \
-              --enable-luainterp=yes \
-              --enable-cscope \
-              --with-x=yes \
-              --disable-gui \
-              --prefix=/usr/local
+    --enable-multibyte \
+    --enable-rubyinterp=yes \
+    --enable-python3interp=yes \
+    --enable-perlinterp=yes \
+    --enable-luainterp=yes \
+    --enable-cscope \
+    --with-x=yes \
+    --disable-gui \
+    --prefix=/usr/local
   sudo make install >/dev/null
 
   vim +PlugInstall +qall
